# Generated by Django 4.1.5 on 2023-01-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Student Name ')),
                ('applicationNo', models.IntegerField(max_length=10, unique=True, verbose_name='Application number')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('deportment', models.CharField(max_length=50, verbose_name='Deportment')),
            ],
            options={
                'verbose_name': 'studentdata',
                'verbose_name_plural': 'studentdatas',
            },
        ),
    ]
