# Generated by Django 4.1.5 on 2023-01-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='applicationNo',
            field=models.IntegerField(unique=True, verbose_name='Application number'),
        ),
    ]
