# Generated by Django 4.1.5 on 2023-01-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_studentdata_applicationno'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentDatas',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Student Name ')),
                ('applicationNo', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Application number')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('deportment', models.CharField(max_length=50, verbose_name='Deportment')),
                ('s1T', models.IntegerField(verbose_name='Educational Psychology theary ')),
                ('s2T', models.IntegerField(verbose_name='Contemporay India and Education theary ')),
                ('s3T', models.IntegerField(verbose_name='Teaching and Learing theary ')),
                ('s4T', models.IntegerField(verbose_name='Language across the Curriculum theary ')),
                ('s5T', models.IntegerField(verbose_name='Pedagogy Subject theary ')),
                ('s1A', models.IntegerField(null=True, verbose_name='Educational Psychology Assignment ')),
                ('s2A', models.IntegerField(verbose_name='Contemporay India and Education Assignment ')),
                ('s3A', models.IntegerField(verbose_name='Teaching and Learing Assignment ')),
                ('s4A', models.IntegerField(verbose_name='Language across the Curriculum Assignment ')),
                ('s5A', models.IntegerField(verbose_name='Pedagogy Subject Assignment ')),
                ('s1LS', models.IntegerField(default=0, verbose_name='Educational Psychology Late Submission Penalty Mark ')),
                ('s2LS', models.IntegerField(default=0, verbose_name='Contemporay India and Education Late Submission Penalty Mark ')),
                ('s3LS', models.IntegerField(default=0, verbose_name='Teaching and Learing Late Submission Penalty Mark ')),
                ('s4LS', models.IntegerField(default=0, verbose_name='Language across the Curriculum Late Submission Penalty Mark ')),
                ('s5LS', models.IntegerField(default=0, verbose_name='Pedagogy Subject Late Submission Penalty Mark ')),
            ],
            options={
                'verbose_name': 'studentdata',
                'verbose_name_plural': 'studentdatas',
            },
        ),
        migrations.DeleteModel(
            name='studentData',
        ),
    ]
