# Generated by Django 4.1.5 on 2023-01-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_deportment_studentdata_average_studentdata_s1total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Average '),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='s1A',
            field=models.IntegerField(blank=True, null=True, verbose_name='Educational Psychology Assignment '),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='s1Total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Educational Psychology Total '),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='s2Total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Contemporay India and Education Total '),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='s3Total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Teaching and Learing Total '),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='s4Total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Language across the Curriculum Total '),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='s5Total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pedagogy Subject Total '),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Mark'),
        ),
    ]
